Mini Project/PresentationLayer/Areas/Admin/Controllers/AdminHimselfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models.ViewModels;
using PresentationLayer.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Security;

namespace PresentationLayer.Areas.Admin.Controllers
{
    public class AdminHimselfController : Controller
    {
        // GET: Admin/AdminHimself

        UserManager<ApplicationUser> UserManager;
        ApplicationDbContext context;
        //Customers existingCustomer;
        AdminViewModel admin;

        public object SessionManager { get; private set; }

        public AdminHimselfController()
        {
            context = new ApplicationDbContext();
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            ApplicationUser adminOrig = UserManager.FindByEmail("mck@gmail.com");
            admin = new AdminViewModel();
            admin.Name = adminOrig.UserName;
            admin.Email = adminOrig.Email;
        }

        public AdminHimselfController(AdminViewModel adminViewModel)
        {
            admin = adminViewModel;
        }

        // GET: Admin/AdminHimself/Details/5
        public ActionResult Details()
        {         
            return View(admin);
        }
        
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login", "Account");
        }
    }
}

Mini Project/PresentationLayer/Areas/Admin/Controllers/VendorController.cs
using BusinessLogicLayer;
using Entities;
using PresentationLayer.CustomFilter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Areas.Admin.Controllers
{
   // [AuthorizeFilter(Roles = "Admin")]
    public class VendorController : Controller
    {

        IValidation validation;

        public VendorController()
        {
            validation = new Validation();
        }
        public VendorController(IValidation validate)
        {
            validation = validate;
        }
        // GET: Admin/Vendor
     
        public ActionResult Index()
        {
            var vendorList = validation.GetAllValidVendors();
            return View(vendorList);
        }

        // GET: Admin/Vendor/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Vendor/Create
        public ActionResult Create()
        {
            return View();
        }

       // POST: Admin/Vendor/Create
       [HttpPost]
        public ActionResult Create(Vendors vendor)
        {
            int result = 0;
            try
            {          
                    result = validation.AddValidVendor(vendor);
                if(result > 0)
                    return RedirectToAction("Index");               
                else
                    return Content("Unable to create vendor");             
            }
            catch(Exception)
            {
                return View();
            }
        }

        // GET: Admin/Vendor/Edit/5
        public ActionResult Edit(int id)
        {
            Vendors vendor = validation.GetAllVendors().First(v => v.VendorID == id);
            return View(vendor);
        }

        // POST: Admin/Vendor/Edit/5
        [HttpPost]
        public ActionResult Edit(Vendors existingVendors, int id)
        {
            try
            {
                int result = validation.UpdateValidVendor(existingVendors, id);
                if (result > 0)
                    return RedirectToAction("Index");
                else
                    return Content("Unable to update vendor");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Vendor/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Admin/Vendor/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Mini Project/PresentationLayer/Areas/Admin/Views/Vendor/Create.cshtml
@model Entities.Vendors

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vendors</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VendorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSTIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GSTIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GSTIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mini Project/PresentationLayer/Areas/Admin/Views/Vendor/Edit.cshtml
@model Entities.Vendors

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vendors</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VendorID)

        <div class="form-group">
            @Html.LabelFor(model => model.VendorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VendorAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GSTIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GSTIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GSTIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mini Project/PresentationLayer/Areas/Admin/Views/Vendor/Index.cshtml
@model IEnumerable<Entities.Vendors>

@{
    ViewBag.Title = "Vendor Details";
}



<h2>List of Vendors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VendorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VendorAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GSTIN)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VendorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VendorAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GSTIN)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VendorID }) 
            @*@Html.ActionLink("Details", "Details", new { id=item.VendorID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VendorID })*@
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back", "Details", "AdminHimself")
</div>